# Generated by Django 4.1.1 on 2022-10-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                (
                    "preamble",
                    models.CharField(max_length=1024, verbose_name="Preamble"),
                ),
                ("body", models.TextField(blank=True, null=True, verbose_name="Body")),
                (
                    "body_as_markdown",
                    models.BooleanField(default=False, verbose_name="As markdown"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Edited"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Deleted")),
            ],
            options={
                "verbose_name": "",
            },
        ),
    ]
