# Generated by Django 4.1.1 on 2022-10-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={},
        ),
    ]
