# Generated by Django 4.1.1 on 2022-10-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainapp", "0003_delete_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Удалён")),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_as_markdown",
                    models.BooleanField(default=False, verbose_name="Способ разметки"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "cover",
                    models.CharField(
                        default="no_image.svg",
                        max_length=25,
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Удалён")),
                ("title", models.CharField(max_length=256, verbose_name="Заголовок")),
                (
                    "preamble",
                    models.CharField(max_length=1024, verbose_name="Вступление"),
                ),
                (
                    "body",
                    models.TextField(blank=True, null=True, verbose_name="Содержимое"),
                ),
                (
                    "body_as_markdown",
                    models.BooleanField(default=False, verbose_name="Способ разметки"),
                ),
            ],
            options={
                "verbose_name": "новость",
                "verbose_name_plural": "новости",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Удалён")),
                ("num", models.PositiveIntegerField(verbose_name="Номер урока")),
                ("title", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "description_as_markdown",
                    models.BooleanField(default=False, verbose_name="Способ разметки"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.course"
                    ),
                ),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
                "ordering": ("course", "num"),
            },
        ),
        migrations.CreateModel(
            name="CourseTeachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="Удалён")),
                ("name_first", models.CharField(max_length=128, verbose_name="Имя")),
                (
                    "name_second",
                    models.CharField(max_length=128, verbose_name="Фамилия"),
                ),
                ("day_birth", models.DateField(verbose_name="Дата Рождения")),
                ("courses", models.ManyToManyField(to="mainapp.course")),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
