# Generated by Django 4.1.1 on 2022-10-08 14:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="news",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
