# Generated by Django 4.1.1 on 2022-10-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_alter_news_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="news",
            managers=[],
        ),
    ]
