# Generated by Django 4.1.1 on 2022-11-12 05:13

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="age"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=authapp.models.users_avatars_path,
                verbose_name="avatar",
            ),
        ),
    ]
