# Generated by Django 4.1.1 on 2022-11-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "CustomUser",
                "verbose_name_plural": "CustomUsers",
            },
        ),
    ]
